import { VerticalBox } from "std-widgets.slint";

export ProgressSlider := Rectangle {
    property<float> maximum: 100;
    property<float> minimum: 0;
    property<float> value;

    callback value-changed(float);

    min-height: 24px;
    min-width: 100px;
    horizontal-stretch: 1;
    vertical-stretch: 0;

    track := Rectangle {
        width: root.width;
        height: parent.height / 6;
        y: (parent.height - height) / 2;
        background: #aaa;
    }

    handle := Path {
        width: height;
        height: parent.height;
        fill: white;
        x: (root.width - handle.width) * (value - minimum)/(maximum - minimum);

        MoveTo {
            x: (parent.width / 2) / 1px;
            y: 0;
        }

        LineTo {
            x: parent.width / 1px;
            y: (parent.height / 2) / 1px;
        }

        LineTo {
            x: (parent.width / 2) / 1px;
            y: parent.height / 1px;
        }

        LineTo {
            x: 0;
            y: (parent.height / 2) / 1px;
        }

        Close {}
    }

    touch := TouchArea {
        property <float> pressed-value;
        pointer-event(event) => {
            if (event.button == PointerEventButton.left && event.kind == PointerEventKind.down) {
                pressed-value = root.value;
            }
        }
        moved => {
            if (enabled && pressed) {
                value = max(root.minimum, min(root.maximum,
                    pressed-value + (touch.mouse-x - touch.pressed-x) * (maximum - minimum) / (root.width - handle.width)));
                root.value-changed(value);
            }
        }
    }
}